### ISSUE TITLE
Shall we rename repo to "dansuma-frontend"?

### ISSUE THREAD

**Issue by gmacario** [kuruho/frontend#1]

**Comment by gmacario** [comment]
@grigio opinions?

**Comment by gmacario** [comment]
BTW @lucabelluccini agreed to rename kuruko/backend to kuruko/dansuma-backend

**Comment by grigio** [comment]
Ok

**Comment by gmacario** [comment]
Thanks @grigio 

I have just updated https://github.com/kuruho/kuruho-pipelines accordingly.

See https://github.com/kuruho/kuruho-pipelines/commit/033e943503e8f5504ba665ada4d874806944139c
